# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  CI: true
  NPM_CONFIG_CACHE: $(Build.SourcesDirectory)/../npm-cache

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    npm run test -- --coverage --watchAll=false
  displayName: 'npm run test'
  
- task: Application security testing@2020
  displayName: 'Checkmarx scan'
  inputs:
    projectName: 'todolist_react_tests'
    enableSastScan: true
    enableDependencyScan: true

- task: PublishTestResults@2
  displayName: 'Test Result'
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'junit.xml'
    failTaskOnFailedTests: true

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  inputs: 
    codeCoverageTool: Cobertura # or JaCoCo
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'
    
# - task: PublishBuildArtifacts@1
#   displayName: 'Pulish build artifacts'
#   inputs:
#     PathtoPublish: '$(System.DefaultWorkingDirectory)'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
